[package]
name = "imagine"
version = "0.0.6"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"
repository = "https://github.com/Lokathor/imagine"
description = "A crate to help with images."

[dependencies]
bytemuck = "1"
miniz_oxide = { version = "0.5", default-features = false, optional = true }

[features]
default = []
alloc = []
all-formats = ["png", "bmp"]
png = ["miniz_oxide"]
bmp = []

[dev-dependencies]
#pixels = "0.8"
pixels = { git = "https://github.com/parasyte/pixels", rev = "4c6682e65bb417cdaa6e9964cbace5369149452d" }
winit = "0.25"

[[example]]
name = "demo"
required-features = ["alloc"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg","docs_rs"]
features = [
  "alloc",
  "all-formats",
]
