[package]
name = "imagine"
version = "0.0.8"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"
repository = "https://github.com/Lokathor/imagine"
description = "A crate to help with images."

[features]
default = []
alloc = ["tagged_bytes/alloc"]
all-formats = ["png", "bmp", "netpbm"]

# Portable Network Graphics
png = ["miniz_oxide"]

# Windows Bitmap
bmp = []

# Covers all the Netpbm files: pbm, pgm, ppm, pnm, pam
netpbm = []

[dependencies]
bytemuck = "1"
miniz_oxide = { version = "0.5", default-features = false, optional = true }
tagged_bytes = "0.0.1"

[dev-dependencies]
#pixels = "0.8"
pixels = { git = "https://github.com/parasyte/pixels", rev = "4c6682e65bb417cdaa6e9964cbace5369149452d" }
winit = "0.25"

[[example]]
name = "demo"
required-features = ["alloc"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg","docs_rs"]
features = [
  "alloc",
  "all-formats",
]
