[package]
name = "imagine"
description = "A crate to help with images."
repository = "https://github.com/Lokathor/imagine"
version = "0.1.0"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"
categories = ["encoding", "no-std"]

autoexamples = false

[features]
default = ["alloc", "png"]
alloc = []
png = [] # Portable Network Graphics
#bmp = [] # Windows Bitmap
#netpbm = [] # Covers all the Netpbm files: pbm, pgm, ppm, pnm, pam

[dependencies]
bytemuck = "1.11"
bitfrob = "0.2.1"
miniz_oxide = { version = "0.5.3", default-features = false, optional = true }

[dev-dependencies]
getrandom = "0.2.7"
walkdir = "2.3.2"
pixels = "0.9"
winit = "0.26"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg","docs_rs"]
all-features = true

[[example]]
name = "png_chunk_print"
required-features = ["png"]

[[example]]
name = "png_viewer"
required-features = ["alloc", "png", "miniz_oxide"]
